apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-agenda.fullname" . }}
  labels:
    {{- include "crud-agenda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    #-port: {{ .Values.service.port }}
    # targetPort: http
    - port: 8088
      targetPort: 8088
    # protocol: TCP
    # name: http
  selector:
    {{- include "crud-agenda.selectorLabels" . | nindent 4 }}
