# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/estudo
spring.datasource.username=estudo
spring.datasource.password=estudo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8088
