# Database connection
spring.datasource.url=jdbc:postgresql://192.168.1.93:5432/estudo
spring.datasource.username=estudo
spring.datasource.password=estudo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8088

# Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
endpoint.health.show-details=always
prometheus.metrics.export.enabled=true
metrics.tags.application=crud-agenda
